#!/bin/sh

if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then
	xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --rate 144
	bspc monitor eDP-1 -d '1' '2' '3' '4'
	bspc monitor HDMI-1-0 -d '5' '6' '7' '8'
else
	bspc monitor eDP-1 -d '1' '2' '3' '4' '5' '6' '7' '8'
fi


bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config bottom_padding 0

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config presel_feedback true

bspc wm --adopt-orphans

bspc rule -r .:*

programs="alacritty_float Onboard feh Viewnior Nm-connection-editor stalonetray Lxappearance Yad"
for rules in $programs; do
   bspc rule -a "$rules" state=floating; done

bspc rule -a alacritty_fullscreen state=fullscreen
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

sh "$HOME/.xinitrc" &

sh "$HOME/.config/cat-configs/bin/system/autostart.sh" &
