
[colors]
draw_bold_text_with_bright_colors = false

[cursor]
# custom_cursor_colors = true
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 84
lines = 24

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
import = ["/home/capitani/.config/cat-configs/alacritty/fonts.toml", "/home/capitani/.config/cat-configs/alacritty/mappings.toml", "/home/capitani/.config/cat-configs/palletes/alacritty/mocha.toml"]
